Models/ChuckNorisJokes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleWebApp.Models
{
    public class ChuckNorisJokes
    {
        public string apiResponse { get; set; }

        public List<string> Categories { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace SimpleWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ChucknorrisController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SimpleWebApp.Models;
using SimpleWebApp1.SimpleUI;

namespace SimpleWebApp1.Controllers
{
    public class ChucknorrisController : Controller
    {
        public ChuckNorisJokes SelectCategories()
        {
            ChuckNorisJokes chuckNorisJokes = new ChuckNorisJokes();
            chuckNorisJokes.Categories = new List<string>();

            chuckNorisJokes.Categories.Add("animal");
            chuckNorisJokes.Categories.Add("Career");
            chuckNorisJokes.Categories.Add("Celebrity");
            chuckNorisJokes.Categories.Add("dev");
            chuckNorisJokes.Categories.Add("explicit");
            chuckNorisJokes.Categories.Add("fashion");
            chuckNorisJokes.Categories.Add("food");
            chuckNorisJokes.Categories.Add("history");
            chuckNorisJokes.Categories.Add("money");
            chuckNorisJokes.Categories.Add("movie");
            chuckNorisJokes.Categories.Add("music");
            chuckNorisJokes.Categories.Add("political");
            chuckNorisJokes.Categories.Add("religion");
            chuckNorisJokes.Categories.Add("science");
            chuckNorisJokes.Categories.Add("sports");
            chuckNorisJokes.Categories.Add("travel");

            return chuckNorisJokes;

        }
        public IActionResult Index()
        {
            ChuckNorisJokes chuckNorisJokes = SelectCategories();
            return View(chuckNorisJokes);
        }

        [HttpPost]
        public ActionResult Index(ChuckNorisJokes chuckNorisJokes, string Categories)
        {
            chuckNorisJokes = SelectCategories();

            if(Categories != null)
            {
                /*Calling the API for chucknorris.io*/
                string apiKey = "CHUCK API";
                HttpWebRequest apiRequest = WebRequest.Create("https://api.chucknorris.io/Jokes/random?" + Categories + "={category}" + apiKey) as HttpWebRequest;

                string apiResponse = "";
                using (HttpWebResponse response = apiRequest.GetResponse() as HttpWebResponse)
                {
                    StreamReader reader = new StreamReader(response.GetResponseStream());
                    apiResponse = reader.ReadToEnd();
                }
                //End 

                //JSON to translate to CSharp
                Randomm category = JsonConvert.DeserializeObject<Randomm>(apiResponse);

                StringBuilder b = new StringBuilder();
                b.Append("<table><tr><th> Chuck </th></tr>");
                b.Append("<tr><td>id</td><td>" + category.id + "</td></tr>" );
                b.Append("<tr><td>id</td><td>" + category.IconUrl + "</td></tr>");
                b.Append("<tr><td>id</td><td>" + category.Url + "</td></tr>");
                b.Append("<tr><td>id</td><td>" + category.Value + "</td></tr>");
                b.Append("</table");
                chuckNorisJokes.apiResponse = b.ToString();
            }

            return View(chuckNorisJokes);
        }
        
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SimpleWebApp.Models;

namespace SimpleWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Chucknorris/Index.cshtml
@{
    ViewData["Title"] = "Chuck Norris";
}

@model SimpleWebApp.Models.ChuckNorisJokes


<div class="container-fluid py-3">

    <div class="row mx-md-n5">

        <div class="col-md-6 px-md-5  d-sm-block align-self-center text-center" id="app">
            <p class="font-weight-dark font-italic align-self-center" style="font-size: 20px">
                <h1>Chuck Noris Jokes</h1>
            </p>
        </div>


        <div class="col-md-6 px-md-5 py-5 d-none d-sm-block align-self-center text-center" style="font-size: 20px" id="me">
            <div class="row">
                <div class="form-group form-row">
                    <div class="col-md-4 p-3 align-self-center">
                        <label for="Category" class="col-form-label font-weight-dark font-italic">Category: </label>
                    </div>
                    <div class="col-md-8 p-4 align-self-center">
                        <select v-model="myModel" class="custom-select py-3">
                            <option v-for="myOption in myOptions" :value="myOption">{{ myOption.Category }}</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>

        <button class="bg-primary" v-on: click ="">Jokes</button>
    </div>

</div>


@section scripts{
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>
    <script src="~/js/main.js"></script>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="container-fluid py-3">

    <div class="row mx-md-n5">

        <div class="col-md-6 px-md-5 d-none d-sm-block align-self-center text-center" id="app">
            <p class="font-weight-dark font-italic align-self-center" style="font-size: 20px">
                Chuck Noris Jokes
            </p>
        </div>

        <div class="col-md-6 px-md-5 py-5 d-none d-sm-block align-self-center text-center" style="font-size: 20px" id="me">
            <div class="row">
                <div class="form-group form-row">
                    <div class="col-md-4 p-3 align-self-center">
                        <label for="Category" class="col-form-label font-weight-dark font-italic">Category: </label>
                    </div>
                    <div class="col-md-8 p-4 align-self-center">
                        <select v-model="myModel" class="custom-select py-3">
                            <option v-for="myOption in myOptions" :value="myOption">{{ myOption.Category }}</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>


@section scripts{
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.11"></script>
    <script src="~/js/main.js"></script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <!--header for the project-->
    <header>
        <!--navbar-->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 text-center">
            <div class="container text-center">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimpleWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chucknorris" asp-action="Index">Logic</a>
                        </li>
                    </ul>
                </div>
            </div>           
        </nav>

        <!--Card for project start-->
        <div class="card text-center d-sm-block align-self-center text-center bg-light" style="height: 300px;">
            <div class="card-body">
                <p class="font-weight-dark font-italic align-self-center" style="font-size: 20px">
                    <h5 class="card-title">
                        Chuck Norris
                    </h5>
                </p>
            </div>
        </div>

    </header>

    <!--Where all the content goes-->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer of my project-->
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SimpleWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>